project:
  type: website

website:
  title: "Al. Tsyplenkov's ğŸ—ºï¸ Portfolio"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: about.qmd
        text: About me
      - href: projects.qmd
        text: My Projects
  page-footer:
    center: "Â© 2025 Aleksandr Tsyplenkov"

format:
  html:
    theme: flatly
    css: styles.css