project:
  type: website

website:
  favicon: "images/favicon_alt.png"
  title: "–ê–ª–µ–∫—Å–∞–Ω–¥—Ä üó∫ –¶—ã–ø–ª–µ–Ω–∫–æ–≤"
  description: "–ü–µ—Ä—Å–æ–Ω–∞–ª—å–Ω—ã–π —Å–∞–π—Ç –∏ –ø–æ—Ä—Ç—Ñ–æ–ª–∏–æ –¶—ã–ø–ª–µ–Ω–∫–æ–≤–∞ –ê–ª–µ–∫—Å–∞–Ω–¥—Ä–∞"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: about.qmd
        text: –û —Å–µ–±–µ
      - href: projects.qmd
        text: –ú–æ–∏ –ø—Ä–æ–µ–∫—Ç—ã
      # - href: tutorials.qmd
      #  text: My Blog
  page-footer:
    left: 
      ¬© 2025 Aleksandr Tsyplenkov
    right:
      - href: https://www.quarto.org
        text: Built with Quarto
    center:
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/altsyplenkov/altsyplenkov.github.io)</span>
  back-to-top-navigation: false
  page-navigation: true
  
language:
  en:
    title: "My Website"
    description: "English description"
  ru:
    title: "–ú–æ–π —Å–∞–π—Ç"
    description: "–†—É—Å—Å–∫–æ–µ –æ–ø–∏—Å–∞–Ω–∏–µ"

format:
  html:
    theme: flatly
    css: styles.css
    mainfont: Tahoma
    footnotes-hover: true