project:
  type: website

website:
  favicon: "images/favicon_alt.png"
  title: "Александр Цыпленков"
  description: "Персональный сайт и портфолио Цыпленкова Александра"
  google-analytics: "G-R2JZFEX79V"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: about.qmd
        text: О себе
      - href: projects.qmd
        text: Мои проекты
      # - href: tutorials.qmd
      #  text: My Blog
  page-footer:
    left: 
      © 2025 Aleksandr Tsyplenkov
    right:
      - href: https://www.quarto.org
        text: Built with Quarto
    center:
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/altsyplenkov/altsyplenkov.github.io)</span>
  back-to-top-navigation: false
  page-navigation: true
  
language:
  en:
    title: "My Website"
    description: "English description"
  ru:
    title: "Мой сайт"
    description: "Русское описание"

format:
  html:
    theme: flatly
    css: styles.css
    mainfont: Tahoma
    footnotes-hover: true