project:
  type: website

website:
  title: "Al. Tsyplenkov's ğŸ—ºï¸ Portfolio"
  description: "Personal website & portfolio of Aleksandr Tsyplenkov"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: about.qmd
        text: About me
      - href: projects.qmd
        text: My Projects
  page-footer:
    center: "Â© 2025 Aleksandr Tsyplenkov"
  back-to-top-navigation: true
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css